---
output: html_document
editor_options: 
  chunk_output_type: inline
---


```{r setup, include = FALSE}
library(tidyverse)
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/tsigall/Repositories/dsan6600")
```

```{r}
games <- read_csv('data/games.csv')
players <- read_csv('data/players.csv')
plays <- read_csv('data/plays.csv')
tackles <- read_csv('data/tackles.csv')
```

```{r}
head(games)
```
```{r}
head(players, 10)
```

```{r}
head(plays)
```

```{r}
head(tackles)
```

```{r}
tackles <- left_join(tackles, games, by = 'gameId')
head(tackles)
```

```{r}
tackles_weekly <- tackles %>% 
  group_by(gameId) %>% 
  summarize(tackles = sum(tackle),
            forcedFumble = sum(forcedFumble),
            week = mean(week)) %>% 
  ungroup() %>% 
  group_by(week) %>% 
  summarize(tackles = mean(tackles),
            forcedFumble = mean(forcedFumble))

ggplot(aes(x = week, y = tackles), data = tackles_weekly) +
  geom_line()

ggplot(aes(x = week, y = forcedFumble), data = tackles_weekly) +
  geom_line()
```

```{r}
leaders <- left_join(tackles, players, by = 'nflId') %>%
  group_by(displayName) %>%
  summarize(total = n()) %>%
  filter(total > 80) %>%
  arrange(desc(total))

ggplot(aes(x = reorder(displayName, total), y = total), data = leaders) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_cartesian(ylim = c(75, max(leaders$total))) +
  xlab("Player Name") +
  ylab("Total Tackles") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

